### PR TITLE
Update and rename data-ingest.md to imports.md

### PR DESCRIPTION
**Pull request by laneymangan**
during Q1 audit, it was decided to remove the data ingest in lieu of a link to import list in hubspot.

### CODE REVIEW

**Comment by AnthonyRollins** [comment]
@thekaveman When you have a moment, I can't figure out why MkDocs failed in this case. It appears to have no conflicts with the base branch but still failed. We can discuss this on our CRM call this week, but curious if there are any fixes here.

**Comment by thekaveman** [comment]
Hey all, the issue is due to a file being deleted (actually, renamed) and that file is still referenced:

* In this commit, a link was added to the menu for `What is a CRM.md`: https://github.com/cal-itp/customer-success/commit/07798ebddae499e1a4a7722112139eefec592e30
* In the next commit that file was renamed to `what-is-a-crm.md`, but the menu link was not updated: https://github.com/cal-itp/customer-success/commit/648d6f16ad32b723ef56bff64f5af258b4dc12fc

So now the site is actually failing to publish at all: https://github.com/cal-itp/customer-success/actions/runs/5684201372/job/15406385172#step:4:101

```log
mkdocs_awesome_pages_plugin.navigation.NavEntryNotFound:
    Nav entry "What is a CRM.md" not found. [/github/workspace/docs/getting-started/.pages]
```

## Fixing this

- [ ] Short term, update the `docs/getting-started/.pages` file to fix the link to the now renamed file
- [ ] Long term, we should add some branch protection rules to prevent this kind of thing. Normally you don't want to commit directly to the `main` branch just in case something breaks, you want to go through a PR that runs all the checks (like this preview) before merging to `main`.

**Comment by AnthonyRollins** [comment]
@thekaveman Would it be okay to merge this one in and then #303 to fix the naming issue mistake? We should have added a commit change to this PR but created a new pull request (#303) to fix the name mistake. Let me know the best way to handle this current situation and this going forward.

**Comment by thekaveman** [comment]
@AnthonyRollins @laneymangan I would just add one more commit here, no need to split that across multiple PRs, since this one isn't even building the preview currently.

**Pull request merged**
